// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace peluqueria.Models;

public partial class AsistenciaEmpleado
{
    public int IdAsistencia { get; set; }

    public int? IdEmpleado { get; set; }

    public DateOnly? DiaAsistencia { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }
}