// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace peluqueria.Models;

public partial class Compra
{
    public int CompraId { get; set; }

    public int? ProveedorId { get; set; }

    public DateOnly? FechaCompra { get; set; }

    public decimal? TotalCompra { get; set; }

    public virtual ICollection<ProductosComprado> ProductosComprados { get; set; } = new List<ProductosComprado>();

    public virtual Proveedore Proveedor { get; set; }
}