// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace peluqueria.Models;

public partial class DetalleVentaProducto
{
    public int IdDetalleProducto { get; set; }

    public int? IdVenta { get; set; }

    public int? IdProducto { get; set; }

    public int Cantidad { get; set; }

    public decimal MontoProducto { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }

    public virtual Venta IdVentaNavigation { get; set; }
}