// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace peluqueria.Models;

public partial class Empleado
{
    public int IdEmpleado { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public string Email { get; set; }

    public DateOnly? FechaContratacion { get; set; }

    public virtual ICollection<AsistenciaEmpleado> AsistenciaEmpleados { get; set; } = new List<AsistenciaEmpleado>();

    public virtual ICollection<Turno> Turnos { get; set; } = new List<Turno>();

    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();
}