// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using peluqueria.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace peluqueria.Models
{
    public partial interface IPeluqueriaContextProcedures
    {
        Task<int> sp_insertar_detalles_ventasAsync(int? id_venta, int? id_producto, int? id_servicio, int? cantidad_prod, int? cantidad_ser, decimal? total_servicio, decimal? total_producto, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_insertar_ventaAsync(int? id_cliente, int? id_empleado, decimal? total, OutputParameter<int?> id_venta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obtener_clientesResult>> sp_obtener_clientesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obtener_empleadosResult>> sp_obtener_empleadosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_ObtenerProductosResult>> sp_ObtenerProductosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_ObtenerServiciosResult>> sp_ObtenerServiciosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_ValidarUsuarioAsync(string nombre_usuario, string contraseña, OutputParameter<int?> existe, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
