// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using peluqueria.AccesoDatos;

namespace peluqueria.Models;

public partial class PeluqueriaContext : DbContext
{
    public PeluqueriaContext(DbContextOptions<PeluqueriaContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }
    public static PeluqueriaContext CreateDbContext()
    {
        var optionsBuilder = new DbContextOptionsBuilder<PeluqueriaContext>();
        optionsBuilder.UseSqlServer(Connect.ConnectionString());

        return new PeluqueriaContext(optionsBuilder.Options);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}