// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace peluqueria.Models;

public partial class Servicio
{
    public int ServicioId { get; set; }

    public string NombreServicio { get; set; }

    public string Descripcion { get; set; }

    public decimal Precio { get; set; }

    public int? CategoriaId { get; set; }

    public virtual CatServicio Categoria { get; set; }

    public virtual ICollection<DetalleVentaServicio> DetalleVentaServicios { get; set; } = new List<DetalleVentaServicio>();
}