// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace peluqueria.Models
{
    public partial class sp_ObtenerServiciosResult
    {
        public string descripcion { get; set; }
        public string nombre_servicio { get; set; }
        [Column("precio", TypeName = "decimal(10,2)")]
        public decimal precio { get; set; }
        public int servicio_id { get; set; }
    }
}
