// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace peluqueria.Models;

public partial class Turno
{
    public int IdTurno { get; set; }

    public DateOnly? Fecha { get; set; }

    public TimeOnly? HoraTurno { get; set; }

    public int? IdCliente { get; set; }

    public string Servicio { get; set; }

    public int? EmpleadoAsignado { get; set; }

    public virtual Empleado EmpleadoAsignadoNavigation { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }
}